In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Requisito 1

Leitura do dataframe MICRODADOS_ENEM_2023

In [65]:
''' colunas = [
    'NU_INSCRICAO',

    #localização
    'SG_UF_PROVA',
    'NO_MUNICIPIO_PROVA',

    # perfil do aluno
    'TP_SEXO',
    'TP_COR_RACA',
    'TP_FAIXA_ETARIA',

    # escola
    'TP_ESCOLA',
    'TP_DEPENDENCIA_ADM_ESC',

    # renda
    'Q006',

    # notas
    'NU_NOTA_CN',
    'NU_NOTA_CH',
    'NU_NOTA_LC',
    'NU_NOTA_MT',
    'NU_NOTA_REDACAO',

    # presença
    'TP_PRESENCA_CN',
    'TP_PRESENCA_CH',
    'TP_PRESENCA_LC',
    'TP_PRESENCA_MT'
] '''

" colunas = [\n    'NU_INSCRICAO',\n\n    #localização\n    'SG_UF_PROVA',\n    'NO_MUNICIPIO_PROVA',\n\n    # perfil do aluno\n    'TP_SEXO',\n    'TP_COR_RACA',\n    'TP_FAIXA_ETARIA',\n\n    # escola\n    'TP_ESCOLA',\n    'TP_DEPENDENCIA_ADM_ESC',\n\n    # renda\n    'Q006',\n\n    # notas\n    'NU_NOTA_CN',\n    'NU_NOTA_CH',\n    'NU_NOTA_LC',\n    'NU_NOTA_MT',\n    'NU_NOTA_REDACAO',\n\n    # presença\n    'TP_PRESENCA_CN',\n    'TP_PRESENCA_CH',\n    'TP_PRESENCA_LC',\n    'TP_PRESENCA_MT'\n] "

In [66]:
'''
df = pd.read_csv(
    '../dados/microdados_enem_2023.csv',
    sep=';',
    encoding='latin-1',
    usecols=colunas
)
'''

"\ndf = pd.read_csv(\n    '../dados/microdados_enem_2023.csv',\n    sep=';',\n    encoding='latin-1',\n    usecols=colunas\n)\n"

Leitura do DataFrame ITENS_PROVA_2023

In [67]:
colunas_itens = [
    'SG_AREA',
    'CO_HABILIDADE',
    'IN_ITEM_ABAN',
    'NU_PARAM_A',
    'NU_PARAM_B',
    'NU_PARAM_C',
    'TX_COR'
]

In [68]:
df_itens = pd.read_csv(
    '../dados/ITENS_PROVA_2023.csv',
    sep=';',
    encoding='latin-1',
    usecols=colunas_itens
)

In [69]:
df_itens.head()

,SG_AREA,CO_HABILIDADE,IN_ITEM_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR
0,LC,14,0,2.20125,0.82582,0.21190,AMARELA
1,LC,23,0,2.43295,0.90091,0.13239,AMARELA
2,LC,26,0,1.95105,-0.13372,0.19557,AMARELA
3,LC,12,0,1.14733,0.38901,0.23027,ROSA
4,LC,8,0,2.25894,1.00728,0.17726,AMARELA

In [70]:
df_itens.shape

(5550, 7)

Criando um dataset tratado e menor do MICRODADOS_ENEM

In [71]:
'''
df.to_csv('../dados/enem_tratado.csv', index=False)
'''

"\ndf.to_csv('../dados/enem_tratado.csv', index=False)\n"

In [72]:
df_enem_tratado = pd.read_csv(
    '../dados/enem_tratado.csv',
    sep=',',
    encoding='latin-1',
)

In [73]:
df_enem_tratado.head(10)

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ESCOLA,TP_DEPENDENCIA_ADM_ESC,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006
0,210059085136,14,M,1,1,NaN,BrasÃ­lia,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,F
1,210059527735,12,M,1,1,NaN,BrasÃ­lia,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,H
2,210061103945,6,F,1,1,NaN,Caxias do Sul,RS,1,1,1,1,502.0,498.9,475.6,363.2,700.0,C
3,210060214087,2,F,3,2,2.0,Fortaleza,CE,1,1,1,1,459.0,508.5,507.2,466.7,880.0,C
4,210059980948,3,F,3,2,2.0,QuixadÃ¡,CE,1,1,1,1,402.5,379.2,446.9,338.3,560.0,B
5,210058061539,6,F,3,1,NaN,IlhÃ©us,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,C
6,210059855122,11,F,3,1,NaN,Petrolina,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,C
7,210058387333,11,M,3,1,NaN,Governador Valadares,MG,0,0,0,0,NaN,NaN,NaN,NaN,NaN,A
8,210059085137,5,F,2,1,NaN,Salvador,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,C
9,210060801601,11,M,1,1,NaN,Batatais,SP,1,1,1,1,564.7,630.3,610.4,680.2,600.0,F

In [74]:
df_enem_tratado.shape

(3933955, 18)

Requisito 2

In [ ]:
# 1. Preparação: Criamos a tabela de dificuldade média por Área
# Aqui pegamos o arquivo de ITENS e resumimos
df_dificuldade = df_itens.groupby('SG_AREA').agg({
    'NU_PARAM_B': 'mean'
}).reset_index()
df_dificuldade.columns = ['SG_AREA', 'DIFICULDADE_MEDIA']

# 2. O MERGE: Integrando as bases
# Vamos criar uma versão do df_enem que tenha uma linha para cada nota (CN, CH, LC, MT)
# para que o merge consiga "colar" a dificuldade correta em cada uma.
# Mas, para manter seu projeto simples e eficiente, vamos adicionar as 4 colunas de uma vez:

# Criamos um dicionário para mapear as dificuldades
mapa_dificuldade = df_dificuldade.set_index('SG_AREA')['DIFICULDADE_MEDIA'].to_dict()

# Criamos as novas colunas no seu DataFrame principal (df_final)
df_final = df_enem_tratado.copy()

df_final['DIF_MT'] = mapa_dificuldade.get('MT')
df_final['DIF_CN'] = mapa_dificuldade.get('CN')
df_final['DIF_CH'] = mapa_dificuldade.get('CH')
df_final['DIF_LC'] = mapa_dificuldade.get('LC')

Integração concluída com sucesso!

In [76]:
df_final.head(10)

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ESCOLA,TP_DEPENDENCIA_ADM_ESC,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,...,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,DIF_MT,DIF_CN,DIF_CH,DIF_LC
0,210059085136,14,M,1,1,NaN,BrasÃ­lia,DF,0,0,...,NaN,NaN,NaN,NaN,NaN,F,1.724463,1.41788,0.642594,0.661782
1,210059527735,12,M,1,1,NaN,BrasÃ­lia,DF,0,0,...,NaN,NaN,NaN,NaN,NaN,H,1.724463,1.41788,0.642594,0.661782
2,210061103945,6,F,1,1,NaN,Caxias do Sul,RS,1,1,...,502.0,498.9,475.6,363.2,700.0,C,1.724463,1.41788,0.642594,0.661782
3,210060214087,2,F,3,2,2.0,Fortaleza,CE,1,1,...,459.0,508.5,507.2,466.7,880.0,C,1.724463,1.41788,0.642594,0.661782
4,210059980948,3,F,3,2,2.0,QuixadÃ¡,CE,1,1,...,402.5,379.2,446.9,338.3,560.0,B,1.724463,1.41788,0.642594,0.661782
5,210058061539,6,F,3,1,NaN,IlhÃ©us,BA,0,0,...,NaN,NaN,NaN,NaN,NaN,C,1.724463,1.41788,0.642594,0.661782
6,210059855122,11,F,3,1,NaN,Petrolina,PE,0,0,...,NaN,NaN,NaN,NaN,NaN,C,1.724463,1.41788,0.642594,0.661782
7,210058387333,11,M,3,1,NaN,Governador Valadares,MG,0,0,...,NaN,NaN,NaN,NaN,NaN,A,1.724463,1.41788,0.642594,0.661782
8,210059085137,5,F,2,1,NaN,Salvador,BA,0,0,...,NaN,NaN,NaN,NaN,NaN,C,1.724463,1.41788,0.642594,0.661782
9,210060801601,11,M,1,1,NaN,Batatais,SP,1,1,...,564.7,630.3,610.4,680.2,600.0,F,1.724463,1.41788,0.642594,0.661782